# Generated by Django 5.2.1 on 2025-05-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateField(db_index=True, unique=True),
        ),
    ]
