services:
  db:
    image: postgres:17-bookworm
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    command: python backend/manage.py runserver 0.0.0.0:8000
    develop:
      watch:
        - path: ./backend/backend
          action: sync
          target: app
        - path: ./backend/pyproject.toml
          action: rebuild
        - path: ./.env
          action: rebuild
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data: